package com.order
import com.kim.drools.model.Order

rule "order_rule_1"
    salience 10
    when
        $order:Order(amount < 100)
    then
        $order.setScore(0);
        System.out.println("订单金额小于100，不计分");
end

rule "order_rule_2"
    when
        $order:Order(amount >= 100 && amount < 500)
    then
        $order.setScore(100);
        System.out.println("订单金额大于100小于500，计100分");
end

rule "order_rule_3"
    when
        $order:Order(amount >= 500 && amount < 1000)
    then
        $order.setScore(500);
        System.out.println("订单金额大于500，计500分");
end

rule "order_rule_4"
    when
        $order:Order(amount >= 1000)
    then
        $order.setScore(1000);
        System.out.println("订单金额大于1000，计1000分");
end